version: '2'
services:
    flowable-idm-app:
        image: flowable/flowable-idm
        external_links:
            - flowable-idm-db:db
        environment:
            - datasource.driver=org.postgresql.Driver
            - datasource.url=jdbc:postgresql://db:5432/flowable
            - datasource.username=flowable
            - datasource.password=flowable
        ports:
            - 8080:8080
    flowable-idm-db:
        extends:
            file: postgres.yml
            service: flowable-idm-postgres