version: '2'
services:
    flowable-ui-idm-app:
        image: flowable/flowable-ui-idm-app
        external_links:
            - flowable-ui-idm-postgres:postgres
        environment:
            - datasource.driver=org.postgresql.Driver
            - datasource.url=jdbc:postgresql://postgres:5432/flowable
            - datasource.username=flowable
            - datasource.password=flowable
        ports:
            - 8080:8080
    flowable-ui-idm-postgres:
        extends:
            file: postgres.yml
            service: flowable-ui-idm-postgres